name: Fourmolu Publish Binary CI

on:
  push:
    tags:
      - "*"
    paths:
      - .github/workflows/fourmolu.yml

env:
  FOURMOLU_VERSION: 0.5.0.1

jobs:
  fourmolu:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            SUFFIX: x86_64-linux.tar.gz
          - os: macOS-latest
            SUFFIX: x86_64-osx.tar.gz

    steps:
      - name: Setup Haskell
        uses: haskell/actions/setup@v1

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-cabal
          cache-version: v1
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ env.cache-version }}-${{ runner.os }}-build-
            ${{ env.cache-version }}-${{ runner.os }}-

      - name: Install fourmolu
        run: cabal install fourmolu-${{ env.FOURMOLU_VERSION }} --installdir=. --install-method=copy --overwrite-policy=always

      - name: Package
        run: 7z a fourmolu-${{ env.FOURMOLU_VERSION }}-${{ matrix.SUFFIX }} fourmolu

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Fourmolu ${{ env.FOURMOLU_VERSION }}
          draft: true
          files: "*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
