name: Fourmolu Publish Binary CI

on:
  push:
    tags:
      - "fourmolu-*"

env:
  FOURMOLU_VERSION: 0.5.0.1
  FOURMOLU_FOLDER_NAME: fourmolu-binaries-$FOURMOLU_VERSION

jobs:
  fourmolu:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            SUFFIX: x86_64-linux.tar.gz
          - os: macOS-latest
            SUFFIX: x86_64-osx.tar.gz

    steps:
      - name: Setup Haskell
        uses: haskell/actions/setup@v1

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-cabal
          cache-version: v1
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ env.cache-version }}-${{ runner.os }}-build-
            ${{ env.cache-version }}-${{ runner.os }}-

      - name: Install fourmolu
        run: cabal install fourmolu-${{ env.FOURMOLU_VERSION }} --installdir=./${{ env.FOURMOLU_FOLDER_NAME }} --install-method=copy --overwrite-policy=always

      - name: Package
        run: 7z a -tzip ${{ env.FOURMOLU_FOLDER_NAME }}-${{ matrix.SUFFIX }} ${{ env.FOURMOLU_FOLDER_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Fourmolu ${{ env.FOURMOLU_VERSION }}
          draft: true
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
